# Reference https://docs.docker.com/compose/compose-file/compose-file-v3/

version: '3.9'

services:
  db:
    image: postgres
    restart: always
    ports:
      - "5432:5432"
    environment:
      POSTGRES_PASSWORD: thisisabadpasswordresetforproduction
  django:
    build:
      context: ./backend
      dockerfile: ./Dockerfile
    command: ["python", "manage.py", "runserver", "0.0.0.0:8000"]
    volumes:
      - ./backend:/code
    ports:
      - "8000:8000"
    depends_on:
      - db
  frontend:
    restart: always
    build:
      context: ./frontend
      dockerfile: ./compose/Dockerfile
    environment:
      - NUXT_HOST=0.0.0.0
      - NUXT_PORT=3000
      - CHOKIDAR_USEPOLLING=true
    env_file:
      - ./frontend/env/.local
    command: "yarn run dev"
    volumes:
      - ./frontend:/code
    ports:
      - "3000:3000"
